### PR TITLE
DATAJPA-1497 Allow to add a special parameter type from a Spring Data JPA extension

### PR DESCRIPTION
**Pull request by reda-alaoui**
This change allows to add a special parameter type by overriding org.springframework.data.jpa.repository.query.JpaParameters.JpaParameter.isBindable()

### CODE REVIEW

**Comment by reda-alaoui** [comment]
Hello?

**Comment by schauder** [comment]
At the very lest this needs some test, demonstrating how to use it.

**Comment by reda-alaoui** [comment]
@schauder , the test you requested has been added.

**Comment by reda-alaoui** [comment]
Ping :)

**Comment by reda-alaoui** [comment]
Ping :)

**Comment by schauder** [comment]
Thanks for your work.
I polished this and merged it into master.

**Pull request closed without merging**
