### PR TITLE
DATAJPA-1067 - Fixed typo in reference documentation

### PR DESCRIPTION
**Pull request by pitzcarraldo**
Renamed collection arguments name of example code in the reference documentation.
One was plural but another was singular.

- [ v ] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [ v ] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAJPA).
- [ v ] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [ v ] You submit test cases (unit or integration tests) that back your changes.
- [ v ] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Pitzcarraldo Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-jpa&pullRequestId=189)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-jpa&pullRequestId=189) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Pitzcarraldo Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-jpa&pullRequestId=189)!

**Comment by olivergierke** [comment]
This PR still seems to be set up erroneously as it includes ton of changes totally unrelated to the ticket linked. Dropping this as the fix is rather trivial.

**Comment by schauder** [comment]
Probably a left over from when we switched master to mean 2.x

**Pull request closed without merging**
