### PR TITLE
support Pageable.unpaged(sort). 

### LINKED ISSUE #3476: Sorting of Pageable.unpaged(sort) is ignored by JPA Repository
I have case when i need unpaged result with sort order. So to implement this i just used Pageable.unpaged method that allows to pass Sort parameter and I am expacting that jpa repository will return unpaged but sorted result. But it is not working cause jpa repostiory ignores sorting for unpaged  request:

```java
@Override
	public Page<T> findAll(Pageable pageable) {

		if (pageable.isUnpaged()) {
			return new PageImpl<>(findAll());
		}

		return findAll((Specification<T>) null, pageable);
	}
```
Is it possible to change behavior to this:
```java
@Override
	public Page<T> findAll(Pageable pageable) {

		if (pageable.isUnpaged()) {
                        if(pageable.getSort().isSorted()) {
                              return new PageImpl<>(findAll(pageable.getSort()));
                        }
			return new PageImpl<>(findAll());
		}

		return findAll((Specification<T>) null, pageable);
	}
```

### PR DESCRIPTION
**Pull request by yoa1226**
#3476

### CODE REVIEW

**Comment by yoa1226** [comment]
#3476

**Comment by quaff** [comment]
You should add corresponding tests.

**Comment by yoa1226** [comment]
> You should add corresponding tests.

ok. I will.

**Comment by yoa1226** [comment]
@quaff hi, I added corresponding tests.

**Comment by christophstrobl** [comment]
Sorry @yoa1226 that one slipped through - closing this one as #3476 has been solved.

**Pull request closed without merging**
