### PR TITLE
Ignore fields containing Optional.empty when performing Query by Example.

### PR DESCRIPTION
**Pull request by gregturn**

### CODE REVIEW

**Review by schauder — CHANGES_REQUESTED** [review]
Can we make the test independent of auditable? Because auditables are just a special case where this problem surfaces.

Also can we have some documentation for this?

**Comment by gregturn** [comment]
Will do.

**Comment by gregturn** [comment]
@schauder I've updated this PR with a non-Auditable based test class.

**Comment by schauder** [comment]
Thanks, that's merged.

**Pull request closed without merging**
