### PR TITLE
Added exists method with specification to `JpaSpecificationExecutor`.

### LINKED ISSUE #2388: Add exists method to JpaSpecificationExecutor
While there is `QueryByExampleExecutor.exists(Example<S> example)` which under the hood builds `Specification` from `Example` to execute exists query, there is no method which accepts `Specification` object to execute exists query.
Implementation is pretty simple and I can provide a PR

### PR DESCRIPTION
**Pull request by DiegoKrupitza**
It is now possible to make existence checks with `Specification`s. This is an addition to checking existence with using an `Example`.

Closes #2388

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by DiegoKrupitza** [comment]
@schauder 
Question becasue of commit (https://github.com/spring-projects/spring-data-jpa/commit/af28245670fb20586f6ad86b1f07277471c2d7e7).

I use the import order and code format file from [here](https://github.com/spring-projects/spring-data-build/tree/main/etc/ide) but it seems to be not correct. Therefore I wanted to ask if this style guide is the correct one (since it is also listed in the contribution guidelines) or am I'm doing something wrong?

**Comment by schauder** [comment]
Thanks

That's merged, polished and ported to 3.0.x.

**Comment by schauder** [comment]
> @schauder Question becasue of commit ([af28245](https://github.com/spring-projects/spring-data-jpa/commit/af28245670fb20586f6ad86b1f07277471c2d7e7)).
> 
> I use the import order and code format file from [here](https://github.com/spring-projects/spring-data-build/tree/main/etc/ide) but it seems to be not correct. Therefore I wanted to ask if this style guide is the correct one (since it is also listed in the contribution guidelines) or am I'm doing something wrong?

That is very much correct, but it requires some extra settings mentioned at the bottom.
Specifically this one seems to be off/missing in your configuration
> Class count to use import with *: 10

**Comment by DiegoKrupitza** [comment]
> > @schauder Question becasue of commit ([af28245](https://github.com/spring-projects/spring-data-jpa/commit/af28245670fb20586f6ad86b1f07277471c2d7e7)).
> > I use the import order and code format file from [here](https://github.com/spring-projects/spring-data-build/tree/main/etc/ide) but it seems to be not correct. Therefore I wanted to ask if this style guide is the correct one (since it is also listed in the contribution guidelines) or am I'm doing something wrong?
> 
> That is very much correct, but it requires some extra settings mentioned at the bottom. Specifically this one seems to be off/missing in your configuration
> 
> > Class count to use import with *: 10

Ok thank you!

**Pull request closed without merging**
