### PR TITLE
Handle newlines in subquery detection

### PR DESCRIPTION
**Pull request by freafrea**
- [V] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [V] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [V] You submit test cases (unit or integration tests) that back your changes.
- [V] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).
- 

Added support for handling newlines in finding of subqueries. Changed . to match newlines in regex.

### CODE REVIEW

**Comment by freafrea** [comment]
This issue is blocking my upgrade to spring 2.7.0. Is there anything I can do to help in merging this?

**Comment by freafrea** [comment]
@gregturn sorry for calling, but this issue blocks upgrading to newer spring boot versions. It is already fixed in at least three seperate PRs (this one, https://github.com/spring-projects/spring-data-jpa/pull/2582, https://github.com/spring-projects/spring-data-jpa/pull/2603).
I don't care which one you will merge, but could you please look into any of them?

**Comment by gregturn** [comment]
The test cases from this PR were merged into https://github.com/spring-projects/spring-data-jpa/commit/f7737014944e606686ca5111574229426ec4484b. Thanks!

**Comment by gregturn** [comment]
Backported to `2.7.x.` and `2.6.x`.

**Pull request closed without merging**
