### PR TITLE
Fix passing 'null' argument to parameter annotated as @NotNull

### PR DESCRIPTION
**Pull request by quaff**
Fix GH-3036

### CODE REVIEW

**Comment by christophstrobl** [comment]
I think we should update the documentation and nullability contract annotations so they document what is currently allowed.

**Comment by gbrehmer** [comment]
this would solve the current Kotlin incompatibility as well

**Comment by christophstrobl** [comment]
thanks for the heads up - moved this one up in the list.

**Comment by christophstrobl** [comment]
Thank you @quaff !

**Pull request closed without merging**
