### PR TITLE
Fix regression that entityManager can not be intercepted

### PR DESCRIPTION
**Pull request by quaff**
Fix GH-2730

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by quaff** [comment]
@mp911de Could you fix this in 3.0.x ASAP?

**Comment by wanghwtaiji** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by gregturn** [comment]
Merged to `main`, backported to `3.1.x` and `3.0.x`

**Comment by gregturn** [comment]
Thanks @quaff!

**Pull request closed without merging**
