### PR TITLE
 DATAJPA-1534 - Wildcard character Escaped in ExampleMatcher

### PR DESCRIPTION
**Pull request by thaveethu-vignesh**
Queries using org.springframework.data.domain.ExampleMatcher(contains, etc) return more results than anticipated when wildcard (%,_,etc) is supplied because wildcard char were not escaped in spring data ExampleMatcher.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@thaveethu-vignesh Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-jpa&pullRequestId=377)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-jpa&pullRequestId=377) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by schauder** [comment]
Thanks for the pull request. The issue is already internally in the making.

**Comment by mrishab** [comment]
@schauder Could you add any link to open issue that has the fix for this?

**Comment by schauder** [comment]
It is this very issue, just not by this PR: https://jira.spring.io/browse/DATAJPA-1534

**Pull request closed without merging**
