### PR TITLE
Use `Assert.notNull` for null check

### PR DESCRIPTION
**Pull request by dukbong**
Use the Assert object for null checks.

- [ ] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [ ] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by mp911de** [comment]
While this seems an improvement, the changed state introduces eager evaluation of `String.format(…)`. I think the code lines stem from a time before `Assert` accepted a message supplier. Care to switch to a lambda syntax providing the message as `() -> String.format(…)`?

**Comment by dukbong** [comment]
> While this seems an improvement, the changed state introduces eager evaluation of `String.format(…)`. I think the code lines stem from a time before `Assert` accepted a message supplier. Care to switch to a lambda syntax providing the message as `() -> String.format(…)`?

Oh my gosh!
Following your suggestion,
using lambda syntax can help avoid unnecessary computation that comes with eager evaluation while optimizing the code.
I really appreciate it. It's an honor to gain such valuable insight from a perspective I hadn't considered before.

**Comment by dukbong** [comment]
> While this seems an improvement, the changed state introduces eager evaluation of `String.format(…)`. I think the code lines stem from a time before `Assert` accepted a message supplier. Care to switch to a lambda syntax providing the message as `() -> String.format(…)`?

Oh my god!
Your feedback helped me revisit eager and lazy evaluation, allowing me to avoid unnecessary computations.
Thank you for helping me improve my code.

**Comment by mp911de** [comment]
We're happy to help. Thanks a lot for the fast turnaround.

**Comment by dukbong** [comment]
> We're happy to help. Thanks a lot for the fast turnaround.

I also appreciate the quick feedback. 😄 
I'll continue to study hard to make great contributions in the future! 📚

**Comment by mp911de** [comment]
Thank you for your contribution. That's merged, polished, and backported now.

**Comment by dukbong** [comment]
> Thank you for your contribution. That's merged, polished, and backported now.

Thank you! I learned something new from today's open source activities!

**Pull request closed without merging**
