### PR TITLE
Rename all EntityManager variables to entityManager in SimpleJpaRepository.

### PR DESCRIPTION
**Pull request by jeomxon**
In the current SimpleJpaRepository, most of the variable names for EntityManager were em.
Changing the variable name of this constructor parameter to em also looks good.

### CODE REVIEW

**Comment by quaff** [comment]
I think the name `entityManager` is better than `em`.

**Comment by jeomxon** [comment]
@quaff 
But In SimpleJpaRepository, most of the variable names for EntityManager were em.
Is it good to change all `em` to `entityManager`?

**Comment by quaff** [comment]
> @quaff But In SimpleJpaRepository, most of the variable names for EntityManager were em. Is it good to change all `em` to `entityManager`?

It's safe to rename private variable, and I prefer to rename all `em` to `entityManager`.

**Comment by jeomxon** [comment]
@quaff 
I rename all EntityManager variables to entityManager in SimpleJpaRepository.
Thank you :)

**Comment by gregturn** [comment]
Thanks @jeomxon! Merged to `main`, backported to `3.1.x` and `3.0.x`.

**Pull request closed without merging**
