### PR TITLE
DATAJPA-1617 - Fix quotation on IsEndingWith in documentation

### PR DESCRIPTION
**Pull request by luvarqpp**
Fixing typo in formatting thing.
- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [ ] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAJPA).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [ ] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by luvarqpp** [comment]
I hope, that jira ticket is optional in case of this small fix. Contribution guideline does not mention what applies to documentation (adoc files) and seems to be related mostly to code.

**Comment by schauder** [comment]
We still need a Jira ticket, but I'll create it in this case. No worries.

**Comment by luvarqpp** [comment]
I would like to add a short remark into https://github.com/spring-projects/spring-data-build/edit/master/CONTRIBUTING.adoc file about significance of jira issues. It would save your time in future when changing commit messages, etc.
Is it possible to use same jira issue for newly proposed (in another browser tab actually) change?

**Comment by schauder** [comment]
I don't think a change to the contribution guidelines is necessary.  We do need a Jira issue and it is clear from the checklist for PRs.

In general though we sometimes do collect multiple small documentation changes in a single Jira issue.

**Comment by luvarqpp** [comment]
Ok, I would extend it with remark at the end of "need for jira issue". Like this:
* Make sure there is a ticket in the bug tracker for the project in our https://jira.spring.io[JIRA] (single char typo in documentation or bugfix with tests, both need jira issue).

At least I know that having jira issue is mandatory also for small things and I will make it next time. 
Should I close this issue?
Thanks.

**Comment by schauder** [comment]
That is merged and backported.

Thanks.

**Pull request closed without merging**
