### PR TITLE
DATAJPA-1679 Support distinct and subqueries with projections

### PR DESCRIPTION
**Pull request by wutzebaer**
- [X ] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATAJPA).
- [ X] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [X ] You submit test cases (unit or integration tests) that back your changes.
- [ X] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@wutzebaer Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-jpa&pullRequestId=414)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-jpa&pullRequestId=414) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@wutzebaer Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-jpa&pullRequestId=414)!

**Comment by schauder** [comment]
I added two tests and merged this.

Thanks for the PR.

**Comment by wutzebaer** [comment]
> 
> 
> I added two tests and merged this.
> 
> Thanks for the PR.

just a thought: wouldn't the 'ungreedy' part make problems, if a column contains the string 'from' ?

**Comment by schauder** [comment]
Oh dear, you are right of course. I undid this change with DATAJPA-1696. Thanks for noting this.

**Comment by wutzebaer** [comment]
Do you think it should work, if we require the 'from' to be followed by a whitespace?
`private static final Pattern PROJECTION_CLAUSE = Pattern.compile("select\\s+(?:distinct\\s+)?(.+?)\\s+from\\s+", Pattern.CASE_INSENSITIVE);`

**Comment by schauder** [comment]
No, it still would fail for cases like `select 'select x from y' from all_tables`. 

In order to fix this one would need a proper parser, not just a bunch of regexes

**Comment by schauder** [comment]
If you want to discuss this further please open a new ticket, because this discussion here will be next to impossible to find.

**Pull request closed without merging**
