### PR TITLE
Add `@NativeQuery` annotation

### PR DESCRIPTION
**Pull request by danvandeee**
Annotation to declare native queries directly on repository methods. NativeQuery acts as a shortcut for @Query(nativeQuery = true)

See #3155

### CODE REVIEW

**Comment by christophstrobl** [comment]
@danvandeee thank you for the PR we'll have a look soon.

**Comment by danvandeee** [comment]
Hi @christophstrobl any update on this? If not needed i am also fine by deleting the implementation

**Comment by christophstrobl** [comment]
thanks for the ping - it's on the list - we've just not yet gotten to it.

**Comment by mp911de** [comment]
Thank you for your contribution. That's merged and polished now.

**Pull request closed without merging**
