### PR TITLE
Drop serialVersionUID from AbstractPersistable.

### PR DESCRIPTION
**Pull request by quaff**
Since serialVersionUID already exists

### CODE REVIEW

**Comment by schauder** [comment]
Could you explain what problem gets solved by making it `Serializable`? Apart from the obvious one of an otherwise out of place `serialVersionUID`?

**Comment by quaff** [comment]
> Could you explain what problem gets solved by making it `Serializable`? Apart from the obvious one of an otherwise out of place `serialVersionUID`?

`serialVersionUID` is present here, I guess someone missed `Serializable` here, `Serializable` has no sin, It's reasonable to mark model as serializable.
If project maintainer object this PR for security concern, please close it and remove unused `serialVersionUID`.

**Comment by mp911de** [comment]
Implementing `Serializable` would suddenly make all subclasses of `AbstractPersistable` serializable which isn't an intended effect. Having `serialVersionUID` helps with the object version and aids subclasses that want to rely on `serialVersionUID` and explicitly make their subclasses serializable. That being said, we should keep things as they are right now.

**Comment by quaff** [comment]
> Implementing `Serializable` would suddenly make all subclasses of `AbstractPersistable` serializable which isn't an intended effect. Having `serialVersionUID` helps with the object version and aids subclasses that want to rely on `serialVersionUID` and explicitly make their subclasses serializable. That being said, we should keep things as they are right now.

It seems `serialVersionUID` doesn't inherited by subclasses.
https://stackoverflow.com/questions/23465613/is-serialversionuid-inherited-by-subclasses-if-i-have-default-serialversionuid

**Review by gregturn — COMMENTED** [review]
Based upon @mp911de 's comments, we're actually going to drop serialVersionUID, and verify that doesn't break anything.

**Comment by gregturn** [comment]
Resolved via 2e30a353.

**Comment by gregturn** [comment]
Backport with d3a12428b75024fd9dd30438bbb89a9fc0d24724.

**Comment by gregturn** [comment]
Backported to 2.4.x with 855bff61e144c84ec58d60573a78054bcca6b37f.

**Pull request closed without merging**
