### PR TITLE
DATAJPA-776 - Allow usage of existing non LEFT joins for sorting.

### PR DESCRIPTION
**Pull request by matthewdfleming**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@matthewdfleming Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-jpa&pullRequestId=155) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@matthewdfleming Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-jpa&pullRequestId=155)!

**Comment by schauder** [comment]
I gave some feed back on the Jira issue: https://jira.spring.io/browse/DATAJPA-776

**Comment by schauder** [comment]
Thanks for the work, and sorry for having this lying around for so long. 

I just closed the issue for which this is a proposed fix.
For reasons see there: https://jira.spring.io/browse/DATAJPA-776

**Pull request closed without merging**
