### PR TITLE
Added logging to SpelExpressionStringQueryParameter 

### PR DESCRIPTION
**Pull request by CCob**
This should help developers debug Spel based parameters not setting correctly.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@CCob Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-jpa&pullRequestId=160) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@CCob Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-jpa&pullRequestId=160)!

**Comment by CCob** [comment]
Done

**Comment by schauder** [comment]
This PR seems hopelessly outdated. 

Sorry for letting it lie for so long.

**Comment by CCob** [comment]
No problem, as long as logging is present now from another commit.  Took me many hours debugging incorrect SpEl parameters due to a silent catch block

**Comment by schauder** [comment]
Yes, that empty catch block should be gone.

**Pull request closed without merging**
