### PR TITLE
1.11.10  Cannot use upper case key word for  @Query to query a projection

### PR DESCRIPTION
**Pull request by shuanshuan**
MyEntity

     @Entity
    public class MyEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String name;
    public Long getId() {
        return id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
     }
    } 

 MyEntityPro

       public interface ActivityPro {
       public String getName();
       }    

MyEntityRepository

    //No aliases found in result tuple! Make sure your query defines aliases!; nested exception is
      @Query("SELECT e FROM MyEntity e ")
      Page<ActivityPro> search2(Pageable pageable);
    
     //working 
      @Query("select e from MyEntity e")
      Page<ActivityPro> search(Pageable pageable);

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@shuanshuan Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-jpa&pullRequestId=259)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-jpa&pullRequestId=259) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@shuanshuan Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-jpa&pullRequestId=259)!

**Comment by olivergierke** [comment]
This looks completely broken or invalid. Please create a new PR and make sure you follow the contribution guidelines. Thanks!

**Comment by shuanshuan** [comment]
@koraktor @olivergierke   version 1.11.10

**Pull request closed without merging**
