### PR TITLE
optimization jpa paging query

### PR DESCRIPTION
**Pull request by Janrin**
optimization jpa paging query

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Janrin Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-jpa&pullRequestId=242)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-jpa&pullRequestId=242) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Janrin Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-jpa&pullRequestId=242)!

**Comment by olivergierke** [comment]
Thanks for your contribution. As indicated in [our contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc), before opening a Pull Request, please create a ticket in our [issue tracker](http://jira.spring.io/browse/DATAJPA) first and elaborate on what you're intending to improve and what the problem is you're trying to solve. Also, not that PRs without proper commit messages describing the changes and test cases accommodating those changes are very unlikely to be accepted.

**Comment by schauder** [comment]
Closing since we never got feedback from the OP

**Pull request closed without merging**
